### ISSUE TITLE
Um hey ! Can I suggest you something ?

### ISSUE THREAD

**Issue by justinjk007** [alphapapa/highlight-function-calls#1]
You can add inline html like this in orgmode
```html
#+html: <a href=https://alphapapa.github.io/dont-tread-on-emacs/><img src="https://alphapapa.github.io/dont-tread-on-emacs/dont-tread-on-emacs-150.png" align="right"/></a>
```

Instead of
```html
#+BEGIN_HTML
<a href=https://alphapapa.github.io/dont-tread-on-emacs/><img src="dont-tread-on-emacs-150.png" align="right"></a>
#+END_HTML
```

**Comment by alphapapa** [comment]
Thanks, but GitHub's Org renderer is picky and not entirely compliant with how it should render.  Figuring out how to make it display properly in both the rendered Org files and in exported HTML has been a process of trial-and-error.  I found what works and it's good enough for me.  :)
